Update signal mutation model to fit new data
genome-nexus/genome-nexus pull request #473
Opened 2020-11-25 23:34 UTC by leexgh

2020-12-08 23:11 UTC, onursumer requested changes
Thanks! A few requests regarding the field names and mixins.

2020-12-09 05:18 UTC, leexgh commented on web/src/main/java/org/cbioportal/genome_nexus/web/mixin/SignalMutationMixin.java
> +    @ApiModelProperty("general_population_stats")
@onursumer Good point. For some fields I couldn't come up with a human-readable description, could you give some suggestions and also double check those I added?

2020-12-09 16:39 UTC, onursumer commented on web/src/main/java/org/cbioportal/genome_nexus/web/mixin/SignalMutationMixin.java
> +    @ApiModelProperty("general_population_stats")
Thanks! I think they look good in general.

Which fields are the ones you couldn't come up with a description? Certain field names are not very clear to me either, so most likely I couldn't come up with anything better. Maybe @inodb can help to improve those descriptions? It's not a big deal at this point though. We can always update the descriptions later.

2020-12-09 21:14 UTC, leexgh reviewed
@inodb Could you take a look at the following description and let me know if there is a better one for them? It would be good if you can double check others also

2020-12-09 21:14 UTC, leexgh commented on web/src/main/java/org/cbioportal/genome_nexus/web/mixin/GeneralPopulationStatsMixin.java
> +    @ApiModelProperty("Counts")
Is "Counts" enough?

2020-12-09 21:14 UTC, leexgh commented on web/src/main/java/org/cbioportal/genome_nexus/web/mixin/GeneralPopulationStatsMixin.java
> +    @ApiModelProperty("Frequencies")
Is "Frequencies" enough?

2020-12-09 21:14 UTC, leexgh commented on web/src/main/java/org/cbioportal/genome_nexus/web/mixin/HrdScoreMixin.java
> +    @ApiModelProperty("Median HRD LST")
Not sure if we should add "Median" here, same for others below

2020-12-09 21:14 UTC, leexgh commented on web/src/main/java/org/cbioportal/genome_nexus/web/mixin/SignalPopulationStatsMixin.java
> +    @ApiModelProperty("European")
The name is referred from here: https://gnomad.broadinstitute.org/faq#how-are-population-names-abbreviated
Does SIGNAL have the same pattern?

2020-12-09 21:14 UTC, leexgh commented on web/src/main/java/org/cbioportal/genome_nexus/web/mixin/StatsByTumorTypeMixin.java
> +    @ApiModelProperty("Median Age at Dx")
Or "Median Age at diagnosis"?

2020-12-09 21:16 UTC, inodb approved these changes

2020-12-09 21:17 UTC, inodb commented
We can address the descriptions later, thanks @leexgh !

2020-12-09 21:18 UTC, onursumer approved these changes

2020-12-09 21:18 UTC, merged