reVUE backend integration
genome-nexus/genome-nexus pull request #657
Opened 2023-01-25 23:13 UTC by aditigopalan

2023-01-25 23:29 UTC, leexgh requested changes

2023-01-25 23:29 UTC, leexgh commented on data/curiousCases/VUEs.json
> +        }
Good to remove these vues that we made up randomly 😅

2023-01-25 23:29 UTC, leexgh commented on data/curiousCases/VUEs.json
> +            "genomicLocation": "4,5,55593576,55593606,ATATAATATATATATAT,-",
Sorry this is just an example string I put here, the real genomic location should be: `4,5,55593576,55593606,CCACAGAAACCCATGTATGAAGTACAGTGGA,-`

2023-01-25 23:29 UTC, leexgh commented on model/src/main/java/org/cbioportal/genome_nexus/model/VUEs.java
> +    public String gethugoGeneSymbol() {
```suggestion
    public String getHugoGeneSymbol() {
```
As well as all getter and setter functions in this file. Could simply delete all and re-generate from vscode

2023-01-25 23:29 UTC, leexgh commented on service/src/main/java/org/cbioportal/genome_nexus/service/internal/VariantAnnotationSummaryServiceImpl.java
> +        System.out.println(vuesList);
Remove print functions

2023-01-25 23:29 UTC, leexgh commented on service/src/main/java/org/cbioportal/genome_nexus/util/jsonReader.java
> +            System.out.println(vues);
Same here we don't need print

2023-01-25 23:29 UTC, leexgh commented on service/src/main/java/org/cbioportal/genome_nexus/service/internal/VariantAnnotationSummaryServiceImpl.java
> +            System.out.println(vuesList);
Same here

2023-01-25 23:29 UTC, leexgh commented on service/src/main/java/org/cbioportal/genome_nexus/service/internal/VariantAnnotationSummaryServiceImpl.java
> +import java.util.HashMap;
HashMap is not used, right? we can remove unused import

2023-01-25 23:54 UTC, leexgh approved these changes

2023-01-26 00:00 UTC, inodb commented on service/src/main/java/org/cbioportal/genome_nexus/service/internal/VariantAnnotationSummaryServiceImpl.java
> +            if (vuesMap.get(transcriptConsequence.getTranscriptId()) != null && vuesMap.get(transcriptConsequence.getTranscriptId()).getVariant().equals(annotation.getVariant()))
does this need a null check for when vuesMap returns nothing?

2023-01-30 18:59 UTC, merged